package scenarios

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import utils.{Common, Environment, Headers}

object Login {
  
  val IdamUrl = Environment.idamURL
  val BaseURL = Environment.baseURL

  val MinThinkTime = Environment.minThinkTime
  val MaxThinkTime = Environment.maxThinkTime

  /*====================================================================================
  *Manage Case Login
  *=====================================================================================*/

  val XUILogin =

    group("XUI_020_Login") {
      exec(http("XUI_020_005_Login")
        .post(IdamUrl + "/login?client_id=xuiwebapp&redirect_uri=" + BaseURL + "/oauth2/callback&state=#{state}&nonce=#{nonce}&response_type=code&scope=profile%20openid%20roles%20manage-user%20create-user%20search-user&prompt=")
        .formParam("username", "#{user}")
        .formParam("password", "#{password}")
        .formParam("azureLoginEnabled", "true")
        .formParam("mojLoginEnabled", "true")
        .formParam("selfRegistrationEnabled", "false")
        .formParam("selfRegistrationEnabled", "false")
        .formParam("_csrf", "#{csrf}")
        .headers(Headers.navigationHeader)
        .headers(Headers.postHeader)
        .check(regex("Manage cases")))

        //Nov 2023: required to capture the xui-webapp cookie and feed it back in after login. We were facing an issue whereby after the first login,
        //subsequent logins were generating a new xui-webapp cookie during the login (rather than using the existing one generated by auth/login),
        //and this was causing issues when making subsequent requests to get jurisdictions, work-basket-inputs, etc, throwing a 401.
        .exec(getCookieValue(CookieKey("xui-webapp").withDomain(BaseURL.replace("https://", "")).saveAs("xuiWebAppCookie")))
        .exec(getCookieValue(CookieKey("XSRF-TOKEN").withDomain(BaseURL.replace("https://", "")).withSecure(true).saveAs("XSRFToken")))

        .exec(Common.configurationui)
        .exec(Common.configJson)
        .exec(Common.TsAndCs)
        .exec(Common.configUI)
        //.exec(Common.userDetails)
        .exec(Common.isAuthenticated)
        .exec(Common.monitoringTools)
    }

    .pause(MinThinkTime , MaxThinkTime)

    //.exec(getCookieValue(CookieKey("xui-webapp").withDomain(BaseURL.replace("https://", "")).saveAs("xuiWebAppCookie")))

    .exec { session =>
      println("****Captured XSRFToken After Login: " + session("XSRFToken").asOption[String].getOrElse("NOT FOUND"))
      println("****Captured WebAppToken After Login: " + session("xuiWebAppCookie").asOption[String].getOrElse("NOT FOUND"))
      session
    }

  val XUILoginCa =

    group("XUI_020_LoginCa") {
      exec(http("XUI_020_005_LoginCa")
        .post(IdamUrl + "/login?client_id=xuiwebapp&redirect_uri=" + BaseURL + "/oauth2/callback&state=#{state}&nonce=#{nonce}&response_type=code&scope=profile%20openid%20roles%20manage-user%20create-user%20search-user&prompt=")
        .formParam("username", "#{userCa}")
        .formParam("password", "#{passwordCa}")
        .formParam("save", "Sign in")
        .formParam("selfRegistrationEnabled", "false")
        .formParam("_csrf", "#{csrf}")
        .headers(Headers.navigationHeader)
        .headers(Headers.postHeader)
        .check(regex("Manage cases")))

        .exec(Common.configurationui)
        .exec(Common.configJson)
        .exec(Common.TsAndCs)
        .exec(Common.configUI)
        .exec(Common.userDetails)
        .exec(Common.isAuthenticated)
        .exec(Common.monitoringTools)
    }

    .pause(MinThinkTime , MaxThinkTime)

  /*====================================================================================
  *PRL Citizen Login
  *=====================================================================================*/

  val PrlLogin = 

    group("PRL_CUI_020_Login") {
      exec(http("PRL_CUI_020_005_Login")
        .post(IdamUrl + "/login?client_id=prl-citizen-frontend&response_type=code&redirect_uri=" + Environment.prlURL + "/receiver")
        .headers(Headers.commonHeader)
        .header("accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9")
        .header("content-type", "application/x-www-form-urlencoded")
        .formParam("username", "#{user}")
        .formParam("password", "#{password}")
        .formParam("save", "Sign in")
        .formParam("selfRegistrationEnabled", "true")
        .formParam("_csrf", "#{csrf}")
        .check(substring("Child arrangements and family injunction cases")))
    }


    .pause(MinThinkTime, MaxThinkTime)

}